#!/usr/bin/env bash
# checkpoint-hourly cron: write a wiki checkpoint file deterministically.
set -u
TS="$(date +%Y-%m-%d-%H)"
WIKI_DIR=~/hermes-wiki/projects/hermes/checkpoints
mkdir -p "$WIKI_DIR"
OUT="$WIKI_DIR/${TS}.md"

K="$(hermes kanban list 2>&1 || echo 'kanban list failed')"
ARTIFACTS="$(find ~/.hermes/artifacts/queen -maxdepth 2 -name events.jsonl -mtime -1 2>/dev/null | head -20 || true)"
HUB=~/.hermes/skills/queen-dispatch/event-hub/scripts/hub.py
NOTIFY="$("$HOME/.hermes/bin/hermes-python" "$HUB" notify --policy default 2>&1 || echo 'hub failed')"

cat > "$OUT" <<HEADER
---
title: Hermes Checkpoint ${TS}
status: draft
updated: $(date +%Y-%m-%d)
type: project
tags: [checkpoint, hermes, autogenerated]
source: cron=c21c48eeeaf7
generated_at: $(date -Iseconds)
---

# Hermes Checkpoint ${TS}

## Cron
- job: checkpoint-hourly (c21c48eeeaf7)
- schedule: 0 * * * *

## Kanban (live)
\`\`\`
$K
\`\`\`

## Recent dispatcher artifacts (last 24h)
\`\`\`
${ARTIFACTS:-none}
\`\`\`

## Event Hub notify (default)
\`\`\`
$NOTIFY
\`\`\`
HEADER

echo "WROTE $OUT"
ls -la "$OUT"
